# Override file for development/local customization
# This file is automatically loaded by docker-compose

version: '3.8'

services:
  qwen-chat:
    # Override environment variables for local development
    environment:
      - MODEL_NAME=Qwen/Qwen2.5-0.5B-Instruct
      - MAX_MEMORY_GB=8
      - DEVICE=cpu  # Use CPU for development
    
    # Override ports for local development
    ports:
      - "8004:8000"  # Backend API (mapped to 8004 to avoid conflict)
      - "3001:3000"  # Frontend (mapped to 3001 to avoid conflict)
    
    # Override volumes for local development
    volumes:
      - ./model_config.json:/app/model_config.json
      - ./simple-frontend.html:/app/simple-frontend.html
      - ./simple-server.py:/app/simple-server.py
      - ./prism-*.js:/app/static/
      - ./prism-*.css:/app/static/
    
    # Override resource limits for development
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G